### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by da-the-dev** [Paultje52/better-mysql#2]
I have `better-mysql` installed via `npm` but I get an error when I launch my Nodejs app:

`Error: Cannot find module '/Users/alexeytkachenko/Documents/PROJECTS/b-r-u-h-Discord-bot/node_modules/better-mysql/src\index.js
Please verify that the package.json has a valid "main" entry`

This module is clearly there, but for some reason, my Nodejs app can't reach it. I use Visual Studio Code and here what it recommends me to do:
```
Could not find a declaration file for module 'better-mysql'.
'/Users/alexeytkachenko/Documents/PROJECTS/b-r-u-h-Discord-bot/node_modules/
better-mysql/src/index.js' implicitly has an 'any' type.
Try 'npm install @types/better-mysql' if it exists or add a new declaration (.d.ts)
file containing 'declare module 'better-mysql';'
```
I tried to create `.d.ts` file, but it didn't work.
I also changed the `main` entry in `package.json` in the `better-mysql` folder.

Any idea what's wrong?

**Comment by Paultje52** [comment]
Hello,
I'm sorry that my response is late, I didn't saw the mail from github.

I think it's a problem with the package.json. What operating system are you using?

**Comment by Paultje52** [comment]
@da-the-dev I'm closing this issue if you haven't responded before 2020-7-5
